steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag', 'gcr.io/${PROJECT_ID}/medigo-backend-api', '--cache-from', 'gcr.io/${PROJECT_ID}/medigo-backend-api:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/medigo-backend-api']
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'run', 'deploy', 'medigo-backend-api',
    '--image', 'gcr.io/${PROJECT_ID}/medigo-backend-api',
    '--region', 'europe-west1',
    '--platform', 'managed',
    '--allow-unauthenticated',
    '--set-env-vars', 'EMAIL_USER=claramagdy60@gmail.com,EMAIL_PASS="aznj srbz woif oibc",SMTP_SERVER=smtp.gmail.com,SMTP_PORT=587'
  ]
images:
- 'gcr.io/${PROJECT_ID}/medigo-backend-api'
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
