steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag', 'gcr.io/${PROJECT_ID}/medigo-backend-api', '--cache-from', 'gcr.io/${PROJECT_ID}/medigo-backend-api:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/medigo-backend-api']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'medigo-backend-api', '--image', 'gcr.io/${PROJECT_ID}/medigo-backend-api', '--region', 'europe-west1', '--platform', 'managed', '--allow-unauthenticated']
images:
- 'gcr.io/${PROJECT_ID}/medigo-backend-api'
options:
  machineType: 'E2_HIGHCPU_8'
